version: '2.1'
volumes:
  shared_folder:
    external: true
services:
  server:
    build:
      context: ./App/server
    restart: on-failure
    privileged: true
    network_mode: host
    ports:
      - '8501:8501'
    volumes:
      - 'shared_folder:./data/'
  smart_lock:
    build:
      context: ./App/smart_lock
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - 'shared_folder:./data/'
  auto_sanitize:
    build:
      context: ./App/auto_sanitize
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - 'shared_folder:./data/'