version: '2'

volumes:
  - shared_folder:
      external: true
  - ./config:
      external: true
services:
  server:
    build: ./AppData/server
    restart: on-failure
    privileged: true
    network_mode: host
    ports:
        - 8501:8501
    volumes:
      - shared_folder:/usr/src/appdata
      - shared_folder:/usr/src/appdata/dataset
  smart_lock:
    build: ./AppData/smart_lock
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - ./config:/usr/src/appdata/
      - shared_folder:/usr/src/appdata
      - shared_folder:/usr/src/appdata/dataset
  auto_sanitize:
    build: ./AppData/auto_sanitize
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - shared_folder:/usr/src/appdata