version: '2'
volumes:
  resin-data:
services:
  server:
    build:
      context: ./App/server
    restart: on-failure
    privileged: true
    network_mode: host
    ports:
      - '8501:8501'
    volumes:
      - 'resin-data:/data'
  smart_lock:
    build:
      context: ./App/smart_lock
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - 'resin-data:/data'

  auto_sanitize:
    build:
      context: ./App/auto_sanitize
    restart: on-failure
    privileged: true
    network_mode: host
    volumes:
      - 'resin-data:/data'